### ISSUE TITLE
Does this work in Python 2.6?

### ISSUE THREAD

**Issue by douglasawh** [thecodeteam/nagios-unity#1]
Any thoughts on the following other than potential Python 2.6 issue?

`/usr/bin/nagios-unity -help
Traceback (most recent call last):
File "/usr/bin/nagios-unity", line 7, in <module>
from nagiosunity.cli.client import main
File "/usr/lib/python2.6/site-packages/nagiosunity/cli/client.py", line 54, in <module>
from nagiosunity import commands
File "/usr/lib/python2.6/site-packages/nagiosunity/commands/__init__.py", line 47
commands_dict = {cmd.name: cmd for cmd in COMMANDS}
^
SyntaxError: invalid syntax`

**Comment by douglasawh** [comment]
I have confirmed this works on python 2.7.12 via pip install

**Comment by peter-wangxu** [comment]
Nagios-unity doesn’t support the old python2.6 currently. The mainstream python version is now 2.7 and 3.5

Additionally, it’s major dependency, storops, doesn’t support python2.6 either. 

I would suggest installing the pyenv and running the py27 in its sandbox.

**Comment by douglasawh** [comment]
I know what you are saying, but CentOS 6 still uses 2.6. Anyway, I no longer work for Nagios, so as far as I'm concerned this can be closed as not fixing or however the project deals with that. Back in early February, I believe I basically told the user on the Nagios forums they'd need 2.7.

**Comment by peter-wangxu** [comment]
Closing it, will not support python2.6.
