### ISSUE TITLE
HTTP Client Error (HTTP 401)

### ISSUE THREAD

**Issue by qbohland** [thecodeteam/nagios-unity#2]
Hello,

I'm trying to monitor a Dell Unity 300 with the nagios-unity but I have an issue.
I have installed nagios-unity but I'm trying to running a command : 
nagios-unity -H 10.0.11.30 -u admin -p xxxxxx battery
(battery or other object)

And the full output:
[log.txt](https://github.com/thecodeteam/nagios-unity/files/1879401/log.txt)

When I'm trying to connect in web interface of the Unity, the web browser asking for a certificate. I can make cancel and use the credentials but maybe the problem come from here ?

And for information, I have just installed nagios-unity with pip install and I didn't make any configuration.

Thanks for any help.

Best regards,
Quentin.

**Comment by peter-wangxu** [comment]
Thanks for reaching out.

It's not related the certificate i believe.

Looks like you specify the wrong username/password, or you don't have the permission to access the system resource(i.e battery)

Thanks
Peter

**Comment by qbohland** [comment]
Hello,

I'm trying with every object but same issue and the username and password are correct because I can login with the web interface...

Best regards,
Quentin.

**Comment by peter-wangxu** [comment]
It's really awkward. Please provide following info:
* Unity Software Version
* User(`admin`) role type
* Try `nagios-unity` on another host

Thanks
Peter

**Comment by MikeW83** [comment]
I have the same issue. I have tried every object. Our software version is 4.2.0.9433914

> Traceback (most recent call last):
>   File "/usr/local/bin/nagios-unity", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/nagiosunity/cli/client.py", line 66, in inner
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/nagiosunity/cli/client.py", line 86, in main
>     return command(cli_opt).check()
>   File "/usr/local/lib/python2.7/dist-packages/nagiosunity/commands/disk.py", line 47, in check
>     self.disks)
>   File "/usr/local/lib/python2.7/dist-packages/nagiosunity/lib/utils.py", line 36, in get_all_status
>     for obj in unity_objects:
>   File "/usr/local/lib/python2.7/dist-packages/storops/lib/resource.py", line 280, in __iter__
>     return iter(self.list)
>   File "/usr/local/lib/python2.7/dist-packages/storops/lib/resource.py", line 261, in list
>     self.update()
>   File "/usr/local/lib/python2.7/dist-packages/cachez.py", line 206, in func_wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/storops/unity/resource/__init__.py", line 292, in update
>     ret = super(UnityResourceList, self).update(data)
>   File "/usr/local/lib/python2.7/dist-packages/cachez.py", line 206, in func_wrapper
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/storops/lib/resource.py", line 227, in update
>     data = self._get_raw_resource()
>   File "/usr/local/lib/python2.7/dist-packages/storops/unity/resource/__init__.py", line 318, in _get_raw_resource
>     nested_fields=nested_fields)
>   File "/usr/local/lib/python2.7/dist-packages/storops/unity/client.py", line 42, in _wrap
>     ret = func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/storops/unity/client.py", line 73, in get_all
>     fields = self.get_fields(type_name, base_fields, nested_fields)
>   File "/usr/local/lib/python2.7/dist-packages/storops/unity/client.py", line 158, in get_fields
>     ret = unity_type.fields
>   File "/usr/local/lib/python2.7/dist-packages/storops/unity/resource/type_resource.py", line 54, in fields
>     ret = tuple(sorted(att['name'] for att in self.attributes))
> TypeError: 'NoneType' object is not iterable

**Comment by qbohland** [comment]
Hello,

My software is in version 4.2.1.9535982
I use the local user admin with the role administrator.
If I try on another device, (like Synology NAS), I have the error of MikeW83. I haven't another Unity. You can see the output in the txt file below:
[loog.txt](https://github.com/thecodeteam/nagios-unity/files/1883438/loog.txt)

Thanks for your time and help.

Best regards,
Quentin.

**Comment by peter-wangxu** [comment]
@qbohland What's the difference of you 2 hosts causing the different result?

@qbohland @MikeW83 what's your python version?

I am going find the 4.2 to run the test as well
Thanks
Peter

**Comment by qbohland** [comment]
Hello !

It's working well now. I have created a new local user and it's working with it. I don't know why it's not working with the admin account. Maybe the special caracters in the password...

To answer at your question, the second host it's not an Unity. So I think it's normal it's not working :)
And my python version is 2.7

Thanks a lot for your help and your great job ;)

Best regards,
Quentin.

**Comment by peter-wangxu** [comment]
That's great.

You can wrap your password by quotes to identify whether the failure was caused by special characters:)

Thanks
Peter

**Comment by qbohland** [comment]
I have tried with quotes like this: -p "password" but same issue...

It doesn't matter but it's a little bit weird...

Best regards,
Quentin.

**Comment by maximeuri** [comment]
Hi,

i've the same problem with nagios-unity module : storops.connection.exceptions.HTTPClientError: HTTP Client Error (HTTP 401)

OS : CentOS 7
python version : 2.7.5
Unity 350F : OS version 4.4 
local user profile : administrator or operator : idem
password of local user with quotes, and differents (special character '@' or '*') : idem

Can you help me ?

Thanks,
Maxime.

**Comment by MikeW83** [comment]
I had to change the password in a more simplified one without special characters. Now it's working for me.

**Comment by maximeuri** [comment]
With 4.4 OS, password policy don't permit password without special character...

**Comment by daggr8** [comment]
I have the same problem. 
CentOS 6.10
Python 2.7.15
Unity 450F with OS 4.2.3.9670635

**Comment by nowx-gh** [comment]
Having the same issue. Versions 4.4.0 and 4.4.1.
There is another thread open from some dell/emc guys.

https://bugs.launchpad.net/cinder/+bug/1800985?comments=all


It seems they getting the same error.
I'm using python3.

Wrapping password in quotes doesn't help. Created new monitoring user with admin role, also doesn't help. Password is as simple as possible. Tried it is '#' and tried it with '_' as special char.

Nothing helps. Maybe there is really a bug in "requests" python module.

**Comment by nowx-gh** [comment]
@peter-wangxu some guys need your help ❤️
